---
- name: Create directories for RKE2 artifacts and configs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ rke2_artifact_dest }}"
    - "{{ rke2_config_dir }}"
    - "{{ rke2_images_dir }}"

- name: Check if offline artifacts exist on controller (AWX)
  ansible.builtin.stat:
     path: "files/rke2-artifacts/{{ hostvars['localhost']['rke2_version'] }}/rke2.linux-amd64.tar.gz"
  delegate_to: localhost
  register: offline_artifact_check

- name: Copy RKE2 offline artifacts from AWX to Node
  ansible.builtin.copy:
    src: "files/rke2-artifacts/{{ hostvars['localhost']['rke2_version'] }}/{{ item }}"
    dest: "{{ rke2_artifact_dest }}/{{ item }}"
    mode: '0755'
  loop:
    - rke2.linux-amd64.tar.gz
    - rke2-images.linux-amd64.tar.zst
    - sha256sum-amd64.txt
    - install.sh
  when: offline_artifact_check.stat.exists

- name: Download RKE2 artifacts directly from GitHub to Node
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ rke2_artifact_dest }}/{{ item.name }}"
    mode: '0755'
  loop:
    - name: rke2.linux-amd64.tar.gz
      url: "https://github.com/rancher/rke2/releases/download/{{ hostvars['localhost']['rke2_version'] }}/rke2.linux-amd64.tar.gz"
    - name: rke2-images.linux-amd64.tar.zst
      url: "https://github.com/rancher/rke2/releases/download/{{ hostvars['localhost']['rke2_version'] }}/rke2-images.linux-amd64.tar.zst"
    - name: sha256sum-amd64.txt
      url: "https://github.com/rancher/rke2/releases/download/{{ hostvars['localhost']['rke2_version'] }}/sha256sum-amd64.txt"
    - name: install.sh
      url: "https://get.rke2.io"
  when: not offline_artifact_check.stat.exists

- name: Place offline images tarball in agent directory
  ansible.builtin.copy:
    src: "{{ rke2_artifact_dest }}/rke2-images.linux-amd64.tar.zst"
    dest: "{{ rke2_images_dir }}/rke2-images.linux-amd64.tar.zst"
    remote_src: true
    mode: '0644'