---
- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Configure Nginx stream block for RKE2 ports
  ansible.builtin.template:
    src: files/lb/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'

- name: Enable and restart Nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true
